export enum TypeDeb {
    LICATUAL = 'LICENCIAMENTOATUAL',
    LICANTER = 'LICENCIAMENTOANTERIOR',
    IPVAATUAL = 'IPVA',
    IPVAANTER = 'IPVAANTERIOR',
    DPVATATUA = 'DPVAT',
    DPVATANTE = 'DPVATANTERIOR',
    MULTA = 'MULTA',
}